In [1]:
# Import the necessary packages
import pandas as pd
import geopandas as gpd
from pathlib import Path
BASE_DIR = Path().resolve().parent.parent

In [2]:
precinct_gdf = gpd.read_file(BASE_DIR / "Shapefile_Data" / "nc_2022_gen_prec" / "nc_gen_22_st_prec.shp")

In [3]:
precinct_gdf

,UNIQUE_ID,COUNTYFP,COUNTYNM,PRECINCT,G22USSDBEA,G22USSGHOH,G22USSLBRA,G22USSOWRI,G22USSRBUD,GSSC03DINM,...,GSSC05RALL,GSAC08DTHO,GSAC08RFLO,GSAC09DSAL,GSAC09RSTR,GSAC10DADA,GSAC10RTYS,GSAC11DJAC,GSAC11RSTA,geometry
0,BURKE---0001,23,BURKE,0001,437,14,21,0,1081,440,...,1034,438,1095,427,1111,435,1099,445,1093,"POLYGON ((1233595.464 737538.312, 1233589.172 ..."
1,STANLY---0003,167,STANLY,0003,503,14,16,2,646,505,...,665,498,672,478,689,495,672,498,669,"POLYGON ((1644857.853 584760.831, 1644768.728 ..."
2,BURKE---0003,23,BURKE,0003,129,4,8,0,492,131,...,469,135,491,129,499,131,496,132,492,"POLYGON ((1220715.101 726879.358, 1220723.026 ..."
3,STANLY---0007,167,STANLY,0007,379,13,21,0,709,388,...,729,396,723,359,762,386,730,380,738,"POLYGON ((1650578.509 584607.573, 1650484.945 ..."
4,STANLY---0008,167,STANLY,0008,478,5,11,0,79,482,...,83,483,82,479,88,483,84,485,82,"POLYGON ((1646657.855 579294.538, 1646677.799 ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2650,ORANGE---WESTWOOD,135,ORANGE,WESTWOOD,1358,10,9,0,97,1356,...,115,1345,116,1302,157,1347,111,1351,109,"POLYGON ((1980358.648 779536.674, 1980323.701 ..."
2651,ALEXANDER---W,3,ALEXANDER,W,207,12,14,2,920,210,...,918,209,928,195,942,207,930,200,936,"POLYGON ((1328877.683 764648.104, 1328959.697 ..."
2652,LENOIR---W,107,LENOIR,W,93,8,7,0,544,87,...,558,91,551,66,582,85,560,82,562,"POLYGON ((2419504.837 485228.828, 2419439.358 ..."
2653,HAYWOOD---WAYNESVILLE WEST,87,HAYWOOD,WAYNESVILLE WEST,379,10,26,0,504,380,...,512,393,510,376,527,386,514,384,520,"POLYGON ((808739.181 660103.212, 808721.741 66..."
2654,CASWELL---YANCEYVILLE,33,CASWELL,YANCEYVILLE,479,5,12,1,488,479,...,512,474,496,460,512,472,499,480,494,"POLYGON ((1922279.006 944060.291, 1922142.357 ..."

In [ ]:
ei_gdf = gpd.read_file(BASE_DIR / "Shapefile_Data" / "NC_2022_Precincts_Education_Income/NC_2022_Precincts_Education_Income.shp")

In [5]:
ei_gdf

,COUNTYNM,PRECINCT,total_vap,under_9g,9_to_12_nd,hs_grad,scol_nd,assoc_deg,bach_deg,grad_deg_p,...,40k_45k,45k_50k,50k_60k,60k_75k,75k_100k,100k_125k,125k_150k,150k_200k,200k_plus,geometry
0,BURKE,0001,4015.0,120.0,274.0,1067.0,1144.0,470.0,722.0,218.0,...,51.0,66.0,304.0,200.0,236.0,279.0,211.0,71.0,35.0,"POLYGON ((1534379.801 4016798.185, 1534378.481..."
1,STANLY,0003,862.0,0.0,65.0,191.0,252.0,122.0,160.0,72.0,...,0.0,0.0,82.0,23.0,74.0,36.0,46.0,11.0,0.0,"POLYGON ((1667015.245 3988177.997, 1666989.967..."
2,BURKE,0003,1173.0,25.0,72.0,593.0,188.0,138.0,144.0,13.0,...,0.0,16.0,59.0,43.0,113.0,32.0,51.0,13.0,15.0,"POLYGON ((1530914.532 4012972.974, 1530908.691..."
3,STANLY,0007,853.0,0.0,78.0,254.0,153.0,162.0,175.0,31.0,...,107.0,42.0,13.0,27.0,52.0,27.0,0.0,26.0,30.0,"POLYGON ((1668776.531 3988383.284, 1668746.453..."
4,STANLY,0008,2232.0,113.0,340.0,1111.0,308.0,127.0,145.0,88.0,...,21.0,53.0,108.0,133.0,114.0,40.0,0.0,0.0,0.0,"POLYGON ((1667808.328 3986580.868, 1667815.691..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2650,ORANGE,WESTWOOD,4883.0,12.0,145.0,408.0,2592.0,143.0,957.0,626.0,...,51.0,54.0,150.0,58.0,166.0,75.0,35.0,67.0,313.0,"POLYGON ((1761364.504 4062917.557, 1761353.432..."
2651,ALEXANDER,W,1614.0,15.0,60.0,538.0,312.0,391.0,158.0,140.0,...,7.0,26.0,23.0,67.0,56.0,89.0,229.0,45.0,25.0,"POLYGON ((1562305.14 4029297.368, 1562332.17 4..."
2652,LENOIR,W,1239.0,19.0,151.0,367.0,219.0,192.0,209.0,82.0,...,0.0,24.0,39.0,76.0,38.0,78.0,43.0,78.0,28.0,"POLYGON ((1909876.654 3991842.995, 1909860.344..."
2653,HAYWOOD,WAYNESVILLE WEST,3200.0,80.0,217.0,783.0,748.0,353.0,575.0,444.0,...,171.0,48.0,95.0,179.0,227.0,162.0,124.0,29.0,129.0,"POLYGON ((1408145.007 3974520.9, 1408139.869 3..."
2654,CASWELL,YANCEYVILLE,2925.0,95.0,487.0,1133.0,378.0,352.0,363.0,117.0,...,91.0,22.0,97.0,201.0,79.0,24.0,57.0,66.0,9.0,"POLYGON ((1736093.794 4110847.77, 1736051.534 ..."

In [6]:
# Voting Data
smithfield = pd.read_csv(BASE_DIR / "Election_Data_Sheets" / "CSV by City" / "smithfield_votes.csv")
asheboro = pd.read_csv(BASE_DIR / "Election_Data_Sheets" / "csv" / "results_pct_20231107.csv")
charlotte = pd.read_csv(BASE_DIR / "Election_Data_Sheets" / "CSV by City" / "charlotte_votes.csv")

In [7]:
smithfield = smithfield[["County", "Precinct", "Contest Group ID", "Contest Type"]]
charlotte = charlotte[["County", "Precinct", "Contest Group ID", "Contest Type"]]
asheboro = asheboro[asheboro['County'] == "RANDOLPH"]
asheboro = asheboro[["County", "Precinct", "Contest Group ID", "Contest Type", "Contest Name"]]

In [8]:
ei_gdf.to_csv("ei_gdf.csv")

### This is some random code I found to print out the Dataframes.
I really wanted to have it by hand, so I found some code from Stack Overflow (website linked in the comments).

In [6]:
# Source - https://stackoverflow.com/a
# Posted by Lak, modified by community. See post 'Timeline' for change history
# Retrieved 2025-11-21, License - CC BY-SA 4.0

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages

def _draw_as_table(df, pagesize):
    alternating_colors = [['white'] * len(df.columns), ['lightgray'] * len(df.columns)] * len(df)
    alternating_colors = alternating_colors[:len(df)]
    fig, ax = plt.subplots(figsize=pagesize)
    ax.axis('tight')
    ax.axis('off')
    the_table = ax.table(cellText=df.values,
                        rowLabels=df.index,
                        colLabels=df.columns,
                        rowColours=['lightblue']*len(df),
                        colColours=['lightblue']*len(df.columns),
                        cellColours=alternating_colors,
                        loc='center',
                        fontsize=14, # Controls the font size
                        cellLoc='center')
    the_table.scale(1, 1.2) # Scales row height to accommodate larger text
    return fig

def dataframe_to_pdf(df, filename, numpages=(1, 1), pagesize=(11, 8.5)):
  with PdfPages(filename) as pdf:
    nh, nv = numpages
    rows_per_page = len(df) // nh
    cols_per_page = len(df.columns) // nv
    for i in range(0, nh):
        for j in range(0, nv):
            page = df.iloc[(i*rows_per_page):min((i+1)*rows_per_page, len(df)),
                           (j*cols_per_page):min((j+1)*cols_per_page, len(df.columns))]
            fig = _draw_as_table(page, pagesize)
            pdf.savefig(fig, bbox_inches='tight')
            
            plt.close()

In [8]:
charlotte = charlotte.iloc[:1000]

In [20]:
# Source - https://stackoverflow.com/a
# Posted by Lak, modified by community. See post 'Timeline' for change history
# Retrieved 2025-11-21, License - CC BY-SA 4.0

#dataframe_to_pdf(smithfield, 'smithfield.pdf')
#dataframe_to_pdf(smithfield, 'smithfield.pdf', numpages=(3, 1))
#dataframe_to_pdf(charlotte, 'charlotte.pdf', numpages=(20, 1))
dataframe_to_pdf(asheboro, 'asheboro.pdf', numpages=(4, 1))

### What do these shapfiles have?
I need to find a shapefile that has precinct name and corresponding number for my merge.

In [9]:
precinct_name_gdf = gpd.read_file(BASE_DIR / "Shapefile_Data" / "SBE_PRECINCTS_20220831" / "SBE_PRECINCTS_20220831.shp")

In [11]:
block_name_gdf = gpd.read_file(BASE_DIR / "Shapefile_Data" / "SBE_PRECINCTS_CENSUSBLOCKS_20220118" / "SBE_PRECINCTS_CENSUSBLOCKS_20220118.shp")

In [14]:
block_name_gdf[block_name_gdf['prec_id'] == "230"]

,id,county_id,prec_id,geoid20,countyfp20,tractce20,blockce20,update_dt,enr_desc,county_nam,to_enr_des,to_prec_id,geometry
0,180209,60,230,371190059221000,119,005922,1000,NaT,230,MECKLENBURG,None,None,"POLYGON ((1405153.755 522261.532, 1405195.308 ..."
330,181395,60,230,371190059231010,119,005923,1010,NaT,230,MECKLENBURG,None,None,"POLYGON ((1409488.134 512826.338, 1409491.805 ..."
728,182869,60,230,371190059221002,119,005922,1002,NaT,230,MECKLENBURG,None,None,"POLYGON ((1403467.432 520335.178, 1403635.903 ..."
11297,203771,60,230,371190059211006,119,005921,1006,NaT,230,MECKLENBURG,None,None,"POLYGON ((1408894.988 523317.001, 1409038.522 ..."
64567,66649,60,230,371190059281047,119,005928,1047,NaT,230,MECKLENBURG,None,None,"POLYGON ((1415474.964 519288.024, 1415506.301 ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
231225,163198,60,230,371190059281007,119,005928,1007,NaT,230,MECKLENBURG,None,None,"POLYGON ((1415886.618 525648.675, 1415913.818 ..."
231593,165067,60,230,371190059232016,119,005923,2016,NaT,230,MECKLENBURG,None,None,"POLYGON ((1407820.687 513190.095, 1407834.688 ..."
233368,170268,60,230,371190059231011,119,005923,1011,NaT,230,MECKLENBURG,None,None,"POLYGON ((1409588.321 513067.868, 1409716.204 ..."
233402,170609,60,230,371190059221005,119,005922,1005,NaT,230,MECKLENBURG,None,None,"POLYGON ((1405123.788 520901.446, 1405201.997 ..."
233453,170481,60,230,371190059281036,119,005928,1036,NaT,230,MECKLENBURG,None,None,"POLYGON ((1419243.07 522695.417, 1419248.441 5..."

In [10]:
precinct_name_gdf

,id,prec_id,enr_desc,county_nam,of_prec_id,county_id,geometry
0,1,0003,ALBEMARLE NUMBER 3,STANLY,None,84,"POLYGON ((1644857.853 584760.831, 1644768.728 ..."
1,2,0003,DREXEL 03,BURKE,None,12,"POLYGON ((1220715.101 726879.358, 1220723.026 ..."
2,22,0019,LINVILLE 01,BURKE,None,12,"POLYGON ((1142032.036 735283.149, 1141893.094 ..."
3,23,0019,RIDENHOUR,STANLY,None,84,"POLYGON ((1590551.101 597789.851, 1590587.761 ..."
4,71,007,007,MECKLENBURG,None,60,"POLYGON ((1465943.013 524872.128, 1465762.759 ..."
...,...,...,...,...,...,...,...
2647,10150,JMV,JAMESVILLE,MARTIN,None,58,"POLYGON ((2656570.989 769941.315, 2656623.057 ..."
2648,10151,GRF,GRIFFINS,MARTIN,None,58,"POLYGON ((2572997.648 730116.69, 2572954.935 7..."
2649,1962,GSN,GOOSE NEST,MARTIN,None,58,"POLYGON ((2489121.775 774862.002, 2489165.442 ..."
2650,2386,RBV,ROBERSONVILLE,MARTIN,None,58,"POLYGON ((2492739.958 755657.848, 2492576.655 ..."
2651,2286,HMT,HAMILTON,MARTIN,None,58,"POLYGON ((2551177.153 770641.314, 2551176.385 ..."