In [1]:
import pandas as pd
from pathlib import Path
BASE_DIR = Path().resolve().parent

charlotte_mayor = pd.read_csv(BASE_DIR / "Election_Data_Sheets" / "csv" / "results_pct_20231107.csv")

In [2]:
charlotte_mayor = charlotte_mayor.loc[charlotte_mayor['County'] == "MECKLENBURG"]

In [4]:
charlotte_mayor = charlotte_mayor.loc[charlotte_mayor['Contest Name'] == "CITY OF CHARLOTTE MAYOR"]

In [5]:
charlotte_mayor

,County,Election Date,Precinct,Contest Group ID,Contest Type,Contest Name,Choice,Choice Party,Vote For,Election Day,One Stop,Absentee by Mail,Provisional,Total Votes,Real Precinct
2903,MECKLENBURG,11/7/23,1,1,C,CITY OF CHARLOTTE MAYOR,Braxton Winston (Write-In),NaN,1,0,0,0,0,0,Y
2904,MECKLENBURG,11/7/23,1,1,C,CITY OF CHARLOTTE MAYOR,Jennifer Roberts (Write-In),NaN,1,0,0,0,0,0,Y
2905,MECKLENBURG,11/7/23,1,1,C,CITY OF CHARLOTTE MAYOR,Ken May (Write-In),NaN,1,0,0,0,0,0,Y
2906,MECKLENBURG,11/7/23,1,1,C,CITY OF CHARLOTTE MAYOR,Misun Kim,REP,1,110,24,0,0,134,Y
2907,MECKLENBURG,11/7/23,1,1,C,CITY OF CHARLOTTE MAYOR,Rob Yates,LIB,1,12,6,0,0,18,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31214,MECKLENBURG,11/7/23,PROVISIONAL,1,C,CITY OF CHARLOTTE MAYOR,Ken May (Write-In),NaN,1,0,0,0,0,0,N
31215,MECKLENBURG,11/7/23,PROVISIONAL,1,C,CITY OF CHARLOTTE MAYOR,Misun Kim,REP,1,0,0,0,36,36,N
31216,MECKLENBURG,11/7/23,PROVISIONAL,1,C,CITY OF CHARLOTTE MAYOR,Rob Yates,LIB,1,0,0,0,11,11,N
31217,MECKLENBURG,11/7/23,PROVISIONAL,1,C,CITY OF CHARLOTTE MAYOR,Vi Lyles,DEM,1,0,0,0,83,83,N
31218,MECKLENBURG,11/7/23,PROVISIONAL,1,C,CITY OF CHARLOTTE MAYOR,Write-In (Miscellaneous),NaN,1,0,0,0,1,1,N

In [6]:
charlotte_vr = pd.read_csv(BASE_DIR / "Election_Data_Sheets" / "nc_data_2023.csv")

In [ ]:
charlotte_vr =

,county_id.x,county_desc.x,voter_reg_num.x,election_lbl,election_desc,voting_method,voted_party_cd,voted_party_desc,pct_label,pct_description,...,sanit_dist_abbrv,sanit_dist_desc,rescue_dist_abbrv,rescue_dist_desc,munic_dist_abbrv,munic_dist_desc,dist_1_abbrv,dist_1_desc,vtd_abbrv,vtd_desc
0,51,JOHNSTON,33187370,11/07/2023,11/07/2023 MUNICIPAL,ELECTION DAY IN-PERSON,DEM,DEMOCRATIC,PR26,EAST SMITHFIELD,...,NaN,NaN,NaN,NaN,CI09,TOWN OF SMITHFIELD,13,PROSECUTORIAL DISTRICT 13,PR26,PR26
1,51,JOHNSTON,33067021,11/07/2023,11/07/2023 MUNICIPAL,ABSENTEE ONESTOP,DEM,DEMOCRATIC,PR28,SOUTH SMITHFIELD,...,NaN,NaN,NaN,NaN,CI09,TOWN OF SMITHFIELD,13,PROSECUTORIAL DISTRICT 13,PR28,PR28
2,51,JOHNSTON,33204631,11/07/2023,11/07/2023 MUNICIPAL,ELECTION DAY IN-PERSON,DEM,DEMOCRATIC,PR24,EAST SELMA,...,NaN,NaN,NaN,NaN,CI09,TOWN OF SMITHFIELD,13,PROSECUTORIAL DISTRICT 13,PR24,PR24
3,51,JOHNSTON,33083621,11/07/2023,11/07/2023 MUNICIPAL,ELECTION DAY IN-PERSON,UNA,UNAFFILIATED,PR28,SOUTH SMITHFIELD,...,NaN,NaN,NaN,NaN,CI09,TOWN OF SMITHFIELD,13,PROSECUTORIAL DISTRICT 13,PR28,PR28
4,51,JOHNSTON,33073420,11/07/2023,11/07/2023 MUNICIPAL,ABSENTEE ONESTOP,DEM,DEMOCRATIC,PR28,SOUTH SMITHFIELD,...,NaN,NaN,NaN,NaN,CI09,TOWN OF SMITHFIELD,13,PROSECUTORIAL DISTRICT 13,PR28,PR28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1191,51,JOHNSTON,33082769,11/07/2023,11/07/2023 MUNICIPAL,ABSENTEE ONESTOP,DEM,DEMOCRATIC,PR26,EAST SMITHFIELD,...,NaN,NaN,NaN,NaN,CI09,TOWN OF SMITHFIELD,13,PROSECUTORIAL DISTRICT 13,PR26,PR26
1192,51,JOHNSTON,33112148,11/07/2023,11/07/2023 MUNICIPAL,ELECTION DAY IN-PERSON,UNA,UNAFFILIATED,PR26,EAST SMITHFIELD,...,NaN,NaN,NaN,NaN,CI09,TOWN OF SMITHFIELD,13,PROSECUTORIAL DISTRICT 13,PR26,PR26
1193,51,JOHNSTON,33104303,11/07/2023,11/07/2023 MUNICIPAL,ELECTION DAY IN-PERSON,UNA,UNAFFILIATED,PR28,SOUTH SMITHFIELD,...,NaN,NaN,NaN,NaN,CI09,TOWN OF SMITHFIELD,13,PROSECUTORIAL DISTRICT 13,PR28,PR28
1194,51,JOHNSTON,33164013,11/07/2023,11/07/2023 MUNICIPAL,ABSENTEE ONESTOP,DEM,DEMOCRATIC,PR28,SOUTH SMITHFIELD,...,NaN,NaN,NaN,NaN,CI09,TOWN OF SMITHFIELD,13,PROSECUTORIAL DISTRICT 13,PR28,PR28
1195,51,JOHNSTON,33086516,11/07/2023,11/07/2023 MUNICIPAL,ABSENTEE ONESTOP,DEM,DEMOCRATIC,PR28,SOUTH SMITHFIELD,...,NaN,NaN,NaN,NaN,CI09,TOWN OF SMITHFIELD,13,PROSECUTORIAL DISTRICT 13,PR28,PR28